type UniteEnseignement {
    code: Int
    domaine: String
    responsable: String
    credits: Int
    semestre: Int
}

type Query {
    allUEs: [UniteEnseignement]
    getUEByCode(code: Int!): UniteEnseignement
    getUEByDomaine(domaine: String!): [UniteEnseignement]
    getUEBySemestre(semestre: Int!): [UniteEnseignement]
}

type Mutation {
    addUniteEnseignement(
        code: Int!
        domaine: String!
        responsable: String!
        credits: Int!
        semestre: Int!
    ): Boolean

    deleteUniteEnseignement(
        code: Int!
    ): Boolean

    updateUniteEnseignement(
        code: Int!
        domaine: String!
        responsable: String!
        credits: Int!
        semestre: Int!
    ): Boolean
}

schema {
    query: Query
    mutation: Mutation
}